"""Normalize FBS team names across CFBD, ESPN, and Odds API display names."""

from __future__ import annotations

# Keys are lowercased lookup strings; values are canonical CFBD-style school names.
_CFB_ALIASES: dict[str, str] = {
    "ole miss": "Ole Miss",
    "mississippi": "Ole Miss",
    "louisiana monroe": "UL Monroe",
    "ul monroe": "UL Monroe",
    "louisiana": "Louisiana",
    "louisiana lafayette": "Louisiana",
    "louisiana ragin' cajuns": "Louisiana",
    "louisiana ragin cajuns": "Louisiana",
    "umass": "UMass",
    "massachusetts": "UMass",
    "utsa": "UTSA",
    "ut san antonio": "UTSA",
    "uconn": "UConn",
    "connecticut": "UConn",
    "usc": "USC",
    "southern california": "USC",
    "southern california trojans": "USC",
    "miami (oh)": "Miami (OH)",
    "miami oh": "Miami (OH)",
    "miami (fl)": "Miami",
    "miami hurricanes": "Miami",
    "pittsburgh": "Pitt",
    "pitt": "Pitt",
    "pittsburgh panthers": "Pitt",
    "appalachian state": "App State",
    "app state": "App State",
    "appalachian state mountaineers": "App State",
    "florida international": "FIU",
    "fiu": "FIU",
    "florida atlantic": "FAU",
    "fau": "FAU",
    "middle tennessee": "Middle Tennessee",
    "middle tennessee state": "Middle Tennessee",
    "middle tennessee blue raiders": "Middle Tennessee",
    "western kentucky": "Western Kentucky",
    "wku": "Western Kentucky",
    "bowling green": "Bowling Green",
    "bowling green state": "Bowling Green",
    "central michigan": "Central Michigan",
    "eastern michigan": "Eastern Michigan",
    "western michigan": "Western Michigan",
    "northern illinois": "Northern Illinois",
    "southern miss": "Southern Miss",
    "southern mississippi": "Southern Miss",
    "texas a&m": "Texas A&M",
    "texas a and m": "Texas A&M",
    "texas a&m aggies": "Texas A&M",
    "texas a&m-commerce": "Texas A&M-Commerce",
    "nc state": "NC State",
    "north carolina state": "NC State",
    "north carolina state wolfpack": "NC State",
    "unc": "North Carolina",
    "north carolina": "North Carolina",
    "north carolina tar heels": "North Carolina",
    "uab": "UAB",
    "alabama-birmingham": "UAB",
    "smu": "SMU",
    "southern methodist": "SMU",
    "byu": "BYU",
    "brigham young": "BYU",
    "tcu": "TCU",
    "texas christian": "TCU",
    "unlv": "UNLV",
    "nevada-las vegas": "UNLV",
    "hawai'i": "Hawaii",
    "hawaii": "Hawaii",
    "hawai'i rainbow warriors": "Hawaii",
    "san josé state": "San Jose State",
    "san jose state": "San Jose State",
    "cal": "California",
    "california": "California",
    "california golden bears": "California",
    "washington": "Washington",
    "washington huskies": "Washington",
    "washington state": "Washington State",
    "washington state cougars": "Washington State",
    "oregon state": "Oregon State",
    "oregon state beavers": "Oregon State",
    "jacksonville state": "Jacksonville State",
    "sam houston": "Sam Houston",
    "sam houston state": "Sam Houston",
    "kennesaw state": "Kennesaw State",
    "james madison": "James Madison",
    "coastal carolina": "Coastal Carolina",
    "georgia southern": "Georgia Southern",
    "georgia state": "Georgia State",
    "old dominion": "Old Dominion",
    "liberty": "Liberty",
    "army": "Army",
    "army black knights": "Army",
    "navy": "Navy",
    "navy midshipmen": "Navy",
    "air force": "Air Force",
    "air force falcons": "Air Force",
    "notre dame": "Notre Dame",
    "notre dame fighting irish": "Notre Dame",
}


def normalize_team_name(name: str) -> str:
    """Map ESPN / Odds API / CFBD variants to a single canonical school name."""
    if not name or not str(name).strip():
        return name
    raw = " ".join(str(name).strip().split())
    key = raw.lower()
    if key in _CFB_ALIASES:
        return _CFB_ALIASES[key]
    return raw
